modLoader = "javafml"
loaderVersion = "[9,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "landmarks"
version = "${version}"
displayName = "Landmarks"
authors = "orlouge"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.landmarks]]
modId = "neoforge"
type = "required"
versionRange = "[21.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.landmarks]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.10,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "landmarks.mixins.json"
